
server:
  port: 4001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smallfish
    url: jdbc:mysql://localhost:3306/funda
    password: SmallFish@1!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
